# -*- coding: utf-8 -*-
"""Baitaptrenlop

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cORdX-GwZVyo8ptxQ4aEg3XCHuV6AO_g
"""

#Cau1
# Nhập giá trị cho a và b
a = float(input("Nhập giá trị cho a: "))
b = float(input("Nhập giá trị cho b: "))

# Tính tổng
tong = a + b

# Tính hiệu
hieu = a - b

# Tính tích
tich = a * b

# Tính thương (kiểm tra chia cho 0)
if b != 0:
    thuong = a / b
else:
    thuong = "Không thể chia cho 0"

# In kết quả
print(f"Tổng của {a} và {b} là: {tong}")
print(f"Hiệu của {a} và {b} là: {hieu}")
print(f"Tích của {a} và {b} là: {tich}")
print(f"Thương của {a} và {b} là: {thuong}")

#Cau2
chuoi = "Hello World"
ky_tu_da_cat = chuoi[2:5] # Lấy ký tự từ chỉ số 2 đến chỉ số 4
print(ky_tu_da_cat)

#Cau3
chuoi_goc = "   Hello World   "
print(f"Chuỗi gốc: '{chuoi_goc}'")
# 1. Xóa khoảng trắng thừa ở đầu và cuối chuỗi
chuoi_da_cat_khoang_trang = chuoi_goc.strip()
print(f"Chuỗi sau khi cắt khoảng trắng: '{chuoi_da_cat_khoang_trang}'")
# 2. Chuyển chuỗi sang dạng hoa
chuoi_hoa = chuoi_da_cat_khoang_trang.upper()
print(f"Chuỗi dạng hoa: '{chuoi_hoa}'")
# 3. Chuyển chuỗi sang dạng thường
chuoi_thuong = chuoi_da_cat_khoang_trang.lower()
print(f"Chuỗi dạng thường: '{chuoi_thuong}'")
# 4. Thay ký tự H thành ký tự J
chuoi_thay_the_H_thanh_J = chuoi_da_cat_khoang_trang.replace('H', 'J')
print(f"Chuỗi sau khi thay 'H' bằng 'J': '{chuoi_thay_the_H_thanh_J}'")

a = float(input("Nhập giá trị cho a: "))
b = float(input("Nhập giá trị cho b: "))
c = float(input("Nhập giá trị cho c: "))
d = float(input("Nhập giá trị cho d: "))

print("\n--- Kết quả kiểm tra điều kiện ---")

#Cau4. In ra “Hello World!” nếu a lớn hơn b.
if a > b:
    print("Hello World!")
else:
    print("a không lớn hơn b.")

#Cau5. In ra “Yes” nếu a bằng b, ngược lại in “No”.
if a == b:
    print("Yes")
else:
    print("No")

#Cau6. In 1 nếu a bằng b, in 2 nếu a > b, in 3 nếu ngược lại.
if a == b:
    print(1)
elif a > b:
    print(2)
else:
    print(3)

#Cau7. In ra “Hello World!” nếu a bằng b và b bằng d.
if a == b and b == d:
    print("Hello World!")
else:
    print("Điều kiện a==b và b==d không đúng.")

#Cau8. In ra “Hello World!” nếu a bằng b hoặc c bằng d.
if a == b or c == d:
    print("Hello World!")
else:
    print("Điều kiện a==b hoặc c==d không đúng.")

#Cau 9
a = float(input("Nhập giá trị cho a: "))
b = float(input("Nhập giá trị cho b: "))

print('yes') if a > b else print('no')
print("A") if a > b else print("=") if a == b else print("B")

#Cau11
# Nhập số lượng phần tử cho mảng a
while True:
    try:
        n = int(input("Nhập số lượng phần tử (n) cho mảng a: "))
        if n <= 0:
            print("Số lượng phần tử phải là số nguyên dương. Vui lòng nhập lại.")
        else:
            break
    except ValueError:
        print("Đầu vào không hợp lệ. Vui lòng nhập một số nguyên.")
# Tạo mảng a với n phần tử
a = []
print(f"\nVui lòng nhập {n} số nguyên cho mảng a:")
for i in range(n):
    while True:
        try:
            element = int(input(f"Nhập phần tử thứ {i+1}: "))
            a.append(element)
            break
        except ValueError:
            print("Đầu vào không hợp lệ. Vui lòng nhập một số nguyên.")
# Tạo mảng b chỉ chứa các phần tử chẵn của a
b = []
for element in a:
    if element % 2 == 0:
        b.append(element)
# In kết quả
print(f"\nMảng a đã tạo là: {a}")
print(f"Mảng b (chỉ chứa các phần tử chẵn của a) là: {b}")

#Cau12
# Khởi tạo tổng
tong_boi = 0
# Lặp qua các số từ 0 đến 999
for i in range(1000):
    # Kiểm tra nếu số đó là bội của 3 hoặc 5
    if i % 3 == 0 or i % 5 == 0:
        tong_boi += i

# In kết quả
print(f"Tổng các số từ 0 đến 999 mà là bội của 3 hoặc 5 là: {tong_boi}")